-- Supercharged Schema V2

-- 1. Products Table (Standard Inventory)
create table if not exists products (
  sku text primary key,
  name text,
  stock_qty integer default 0
);

-- 2. Orders Table (With Payment Code & Status)
create table if not exists orders (
  id uuid default gen_random_uuid() primary key,
  customer_email text not null,
  order_code text not null, -- Manual lookup code (e.g. HAR-429)
  items jsonb not null, -- Array of { sku, quantity, price }
  status text default 'pending_payment', -- pending_payment, paid, cancelled, expired
  total numeric,
  created_at timestamp with time zone default now()
);

-- Enable Realtime
alter publication supabase_realtime add table products;

-- 3. The "Place Order" Transaction (RPC)
-- Handles stock deduction and order creation safely.
create or replace function place_order(
  order_items jsonb,
  customer_email text,
  payment_code text, -- Generated by frontend (e.g. HAR-123)
  order_total numeric
) returns jsonb as $$
declare
  item jsonb;
  qty int;
  sku_chk text;
  stock_avail int;
  new_order_id uuid;
begin
  -- Loop through items to verify and deduct stock
  for item in select * from jsonb_array_elements(order_items) loop
    sku_chk := item->>'sku';
    qty := (item->>'quantity')::int;

    if sku_chk is null then raise exception 'SKU missing in item'; end if;

    -- Lock row for update
    select stock_qty into stock_avail from products where sku = sku_chk for update;
    
    if stock_avail is null then raise exception 'Product % not found', sku_chk; end if;
    if stock_avail < qty then raise exception 'Insufficient stock for %', sku_chk; end if;

    -- Deduct stock
    update products set stock_qty = stock_qty - qty where sku = sku_chk;
  end loop;

  -- Create the Order
  insert into orders (customer_email, order_code, items, status, total)
  values (customer_email, payment_code, order_items, 'pending_payment', order_total)
  returning id into new_order_id;

  return jsonb_build_object('order_id', new_order_id, 'status', 'success');
end;
$$ language plpgsql;


-- 4. Admin Action: Release Stock (Manual)
-- Returns stock for a cancelled order and updates status.
create or replace function admin_release_stock(
  target_order_id uuid
) returns void as $$
declare
  ord record;
  item jsonb;
  sku_chk text;
  qty int;
begin
  -- Get order
  select * into ord from orders where id = target_order_id;
  
  if ord.status = 'cancelled' or ord.status = 'expired' then
    raise exception 'Order is already cancelled/expired';
  end if;

  -- Loop items and restore stock
  for item in select * from jsonb_array_elements(ord.items) loop
    sku_chk := item->>'sku';
    qty := (item->>'quantity')::int;
    
    update products set stock_qty = stock_qty + qty where sku = sku_chk;
  end loop;

  -- Update status
  update orders set status = 'cancelled' where id = target_order_id;
end;
$$ language plpgsql;


-- 5. Auto-Release Job (Cron) for Unpaid Orders > 1 Hour
-- NOTE: Requires pg_cron extension enabled in Supabase Dashboard -> Database -> Extensions
-- If you cannot enable pg_cron, you must run this logic via a scheduled Edge Function.

-- Enable extension
create extension if not exists pg_cron;

-- Schedule the job to run every 10 minutes
-- Schedule the job to run every 10 minutes
select cron.schedule(
  'auto_release_unpaid', -- Job name
  '*/10 * * * *',        -- Schedule (Every 10 mins)
  $cron$
    do $$
    declare
      r record;
      item jsonb;
    begin
      -- Find expired orders (older than 1 hour, still pending)
      for r in select * from orders where status = 'pending_payment' and created_at < now() - interval '1 hour' loop
        
        -- Restore stock for each item
        for item in select * from jsonb_array_elements(r.items) loop
           update products set stock_qty = stock_qty + (item->>'quantity')::int 
           where sku = (item->>'sku');
        end loop;

        -- Mark as expired
        update orders set status = 'expired' where id = r.id;
        
      end loop;
    end;
    $$;
  $cron$
);
